CREATE DATABASE CSE_3A_161

--CREATE TABLE DEPOSITE--

CREATE TABLE DEPOSITE(
ACTNO INT,
CNAME VARCHAR(50),
BNAME VARCHAR(50),
AMOUNT DECIMAL(8,2),
ADATE DATETIME
)

--INSERT VALUES IN TABLE---

INSERT INTO DEPOSITE VALUES
(101 ,'ANIL','VRCE',1000,'1995-3-1'),
(104,'SUNIL','AJNI',5000,'1996-4-1'),
(103,'MEHUL','KAROLBAGH',3500,'1995-11-17'),
(104,'MADHURI','CHANDI',1200,'1995-12-17'),
(105,'PRAMOD','M.G. ROAD',3000,'1996-3-27'),
(106,'SANDIP','ANDHERI',2000,'1996-3-31'),
(107,'SHIVANI','VIRAR',1000,'1995-9-5'),
(108,'KRANTI','NEHRU PLACE',5000,'1995-7-2'),
(109,'MINU','POWAI',7000,'1995-8-10')



SELECT * FROM DEPOSITE

--CREATE TABLE BRANCH--

CREATE TABLE BRANCH(
BNAME VARCHAR(50),
CITY VARCHAR(50)
)

--INSERT VALUES IN TABLE BRANCH--

INSERT INTO BRANCH VALUES
('VRCE','NAGPUR'),
('AJNI','NAGPUR'),
('KAROLBAGH','DELHI'),
('CHANDI','DELHI'),
('DHARAMPETH','NAGPUR'),
('M.G.ROAD','BANGLORE'),
('ANDHERI','BOMBAY'),
('VIRAR','BOMBAY'),
('NEHRU PLACE','DELHI'),
('POWAI','BOMBAY')

SELECT * FROM BRANCH

--CREATE TABLE CUSTOMERS--

CREATE TABLE CUSTOMERS(
CNAME VARCHAR(50),
CITY VARCHAR(50)
)

--INSERT VALUES IN TABLE CUSTOMERS--

INSERT INTO CUSTOMERS VALUES
('ANIL','CALCUTTA'),
('SUNIL','DELHI'),
('MEHUL','BARODA'),
('MANDAR','PATNA'),
('MADHURI','NAGPUR'),
('PRAMOD','NAGPUR'),
('SANDIP','SURAT'),
('SHIVANI','BOMBAY'),
('KRANTI','BOMBAY'),
('NAREN','BOMBAY')

SELECT * FROM CUSTOMERS

SELECT * FROM BORROW




